language: cpp
cache: apt
env:
  matrix:
     #- UBUNTU_DIST=xenial
     #  BUILD_TYPE=Release
     # - UBUNTU_DIST=trusty
     #   BUILD_TYPE=Release
     - UBUNTU_DIST=bionic
       BUILD_TYPE=Release
     
services:
  - docker

install: true

script:
  - docker build --build-arg UBUNTU=${UBUNTU_DIST} --build-arg BUILD_TYPE=${BUILD_TYPE} -t hassaanirshad/occam:latest -f docker/occam.Dockerfile .

  - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] ;
        then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          && docker push hassaanirshad/occam:latest;
     fi '
